### ISSUE TITLE
Error attempting to insert GUID

### ISSUE THREAD

**Issue by kramii** [fschneidereit/VSEssentials#2]
When I click Edit>Advanced>Insert New Guid, an error dialog is displayed by Visual Studio. The error message says, "Could not load file or assembly 'Microsoft.VisualStudio.Text.UI, Version 15.0.0.0...' or one of its dependencies. The system cannot find the file specified.

**Comment by fschneidereit** [comment]
What version of Visual Studio is causing the error?

**Comment by fschneidereit** [comment]
Couldn't reproduce the issue, closed for now.
