### ISSUE TITLE
Menu item not displayed and shortcut doesn't work on VS2017 Professional 

### ISSUE THREAD

**Issue by YounesCheikh** [fschneidereit/VSEssentials#4]
The menu item is not displayed in the advanced sub-menu of Edit on Visual Studio Professional 2017.
I tried using the keyboard shortcuts but doesn't work. does it work when Resharper is installed? 

![Screenshot](https://content.screencast.com/users/YounesCheikh/folders/Jing/media/fabf9a05-9913-4a49-a9d6-f40cf88dd730/2018-07-27_1643.png)

**Comment by fschneidereit** [comment]
Closed for now because I wasn't able to reproduce the error.
