### ISSUE TITLE
Insert GUID Command distribute old version

### ISSUE THREAD

**Issue by MaceWindu** [fschneidereit/VSEssentials#8]
https://marketplace.visualstudio.com/items?itemName=florians.InsertGUIDCommand

Despite description, downloaded vsix has 2017.1.1 version.

This leads to VS2017 showing update available but clicking update doesn't update anything. As workaround, downloading extension manually from https://github.com/fschneidereit/VSEssentials/releases/tag/v2019.0.0 helps

**Comment by fschneidereit** [comment]
I re-uploaded the current VSIX, should be fixed now.
